#!/bin/sh

set -eu

rc_file="$HOME/.bashrc"
profile_file="$HOME/.profile"
tmp_rc_file="$(mktemp)"
inject_rc_pattern="# If not running interactively, don't do anything"
inject_profile_pattern="# set PATH so it includes user's private bin if it exists"
paths_file="\$HOME/.paths"

update_rc() {
    line="$(grep -n "$inject_rc_pattern" "$rc_file" | sed "s/:.*\$//" | head -n1)"
    prev_line="$((${line} - 1))"

    head -n"$prev_line" "$rc_file" > "$tmp_rc_file"
    cat <<- EOM | cat >> "$tmp_rc_file"
__load_paths() {
    if [ ! -e "${paths_file}" ]; then
        return
    fi

    for l in \$(cat "\$1"); do
        l="\$(eval "echo \$l")"
        if [ -d "\$l" ]; then
            PATH="\$l:\$PATH"
        fi
    done
}
__load_paths "${paths_file}"
unset __load_paths

EOM
    tail -n+"$line" "$rc_file" >> "$tmp_rc_file"
    mv "$tmp_rc_file" "$rc_file"
    rm -f "$tmp_rc_file"
}

update_profile() {
    lines="$(grep -n "$inject_profile_pattern" "$profile_file" | sed "s/:.*\$//")"
    args=""
    for l in $lines; do
        args="$l,$(($l+3))d;$args"
    done
    sed -i -e "$args" "$profile_file"
}

update_rc
update_profile
